### ISSUE TITLE
Logo Design: FlickrBrowser

### ISSUE THREAD

**Issue by baranpirincal** [leonbec/FlickrBrowser#1]
Hey! I saw that your project has no logo design yet. If you interested I can contribute to your project with making logo design and I would be very happy. I am waiting feedback from you! :)

Best Regards
Baran Pirinçal

**Comment by wenfangdu** [comment]
Yeah, would appreciate your contribution:) @baranpirincal

**Comment by baranpirincal** [comment]
@dwfg 

Do you have an any idea about design decisions?

**Comment by wenfangdu** [comment]
Nah, anything you think suitable is fine, it's just a hobby project :P

**Comment by wenfangdu** [comment]
@baranpirincal Hi, are you still working on it? if not, please close the issue.
